[package]
name = "wallet_balance"
version = "0.1.0"
edition = "2021"

[dependencies]
bitcoin = "0.32.4"
reqwest = { version = "0.12.9", features = ["blocking", "json"] }
rust_decimal = "1.36.0"
secp256k1 = "0.30.0"
serde_json = "1.0.132"
xyzpub = "0.3.0"
